# 2.1 数据操作

## 2.1.1 入门

In [1]:
import torch

张量表示由一个数值组成的*数组*，这个数组可能有多个维度。

具有一个轴的张量对应数学上的向量（vector）。

具有两个轴的张量对应数学上的矩阵（matrix）。

具有两个轴以上的张量没有特殊的数学名称。

### arange()创建一个行向量x。
这个行向量包含从0开始的前12个整数，它们被默认创建为浮点数。
张量中的每个值都称为张量的元素（element）

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### shape属性来访问张量的形状 （沿每个轴的长度）

In [3]:
x.shape

torch.Size([12])

### numel()检查其size，一直都是个标量

In [4]:
x.numel()

12

### reshape()改变张量的形状，从一维到多维，不改变元素的值

In [5]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### zeros()创建全为0的张量

In [6]:
tmp = torch.zeros((2,3,4)) #torch.zeros(2，3，4) 
tmp

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

### ones()创建全为1的张量

In [7]:
tmp = torch.ones(2,3,4)
tmp

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

### randn()随机初始化参数，正太分布中的随机取样,[0,1]

In [8]:
tmp = torch.randn(3,4)
tmp

tensor([[-0.1182, -0.4917, -0.1352, -0.7269],
        [-3.1242,  0.3857,  0.3846, -0.0073],
        [ 0.9243,  0.0215,  0.4484,  1.0152]])

### tensor()自定义给张量赋值
几个维度就有几个[]

In [3]:
tmp = torch.tensor([[[1,2,3],[3,3,4]]])#注意tensor只有一个位置[]
tmp,tmp.shape

(tensor([[[1, 2, 3],
          [3, 3, 4]]]),
 torch.Size([1, 2, 3]))

## 2.1.2 运算

### 标准算术运算符（+、-、*、/和**）
对于任意具有相同形状的张量，常见的标准算术运算符（+、-、*、/和**）都可以被升级为按元素运算

In [10]:
x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([2, 2, 2, 2])
tmp = torch.exp(x)#求指数运算符
x + y, x - y, x * y, x / y, x ** y, tmp# **运算符是求幂运算

(tensor([3, 4, 5, 6]),
 tensor([-1,  0,  1,  2]),
 tensor([2, 4, 6, 8]),
 tensor([0.5000, 1.0000, 1.5000, 2.0000]),
 tensor([ 1,  4,  9, 16]),
 tensor([ 2.7183,  7.3891, 20.0855, 54.5981]))

### cat()多个张量连结（concatenate）
第一个输出张量的轴-0长度（\(6\)）是两个输入张量轴-0长度的总和（\(3 + 3\)）；

第二个输出张量的轴-1长度（\(8\)）是两个输入张量轴-1长度的总和（\(4 + 4\)）。

In [9]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X.shape,Y.shape,torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(torch.Size([3, 4]),
 torch.Size([3, 4]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

### == 判断张量位置是否相等

In [12]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

### sum()张量所有元素求和

In [13]:
X.sum()

tensor(66.)

## 2.1.3 广播机制
形状不同的张量，调用广播机制执行元素操作，工作方式如下：

首先，通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状。

其次，对生成的数组执行按元素操作。

In [14]:
# 维度都是二维
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b,a + b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

## 2.1.4 索引和切片
用[-1]选择最后一个元素，可以用[1:3]选择第二个和第三个元素

In [15]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

### 索引元素赋值

In [16]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 2.1.5 节省内存
用Python的id()函数演示了这一点，它给我们提供了内存中引用对象的确切地址。

运行Y = Y + X后，我们会发现id(Y)指向另一个位置。

这是因为Python首先计算Y + X，为结果分配新的内存，然后使Y指向内存中的这个新位置

In [17]:
print('before_id(Y):', id(Y))
before = id(Y)
Y = Y + X
print('after_id(Y):', id(Y))
display(id(Y) == before)

before_id(Y): 139753755135168
after_id(Y): 139753755116304


False

使用切片表示法将操作的结果分配给先前分配的数组,减少内存开销
### zeors_like()分配一个形状一样的全为0的张量

In [18]:
Z = torch.zeros_like(Y)
print('before_id(Z):', id(Z))
Z[:] = X + Y
print('after_id(Z):', id(Z))

before_id(Z): 139753755047872
after_id(Z): 139753755047872


## 2.1.6 转换为其他Python对象

### numpy() tensor() 类型切换

In [19]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)


(numpy.ndarray, torch.Tensor)

### item()函数或者Python内置函数
将大小为1的张量转换为Python标量

In [20]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 2.1.7 小节
* 深度学习存储和操作数据的主要接口是张量（\(n\)维数组）。它提供了各种功能，包括基本数学运算、广播、索引、切片、内存节省和转换其他Python对象。

## 2.1.8 练习


1.运行本节中的代码。将本节中的条件语句X == Y更改为X < Y或X > Y，然后看看你可以得到什么样的张量。

2.用其他形状（例如三维张量）替换广播机制中按元素操作的两个张量。结果是否与预期相同？


### 作业1

In [21]:
X < Y

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [22]:
X > Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

### 作业2??\
张量

In [47]:
a = torch.tensor([[2,3,4], [1,2,3], [3,4,5]])
b = torch.tensor([[1,2,3], [1,2,3]])
a + b

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0