# 2.3 线性代数

## 2.3.1 标量
标量（scalar）仅包含一个数值，由只有一个元素的张量表示

变量（variable），它们表示未知的标量值。

In [2]:
import torch

x = torch.tensor([3.0]) 
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

## 2.3.2 向量
将向量视为标量值组成的列表。我们将这些标量值称为向量的元素（element）或分量（component）

In [4]:
x = torch.arange(4) 
x, x[3]

(tensor([0, 1, 2, 3]), tensor(3))

## 2.3.3 长度、维度和形状

### len()访问张量的长度

In [5]:
len(x)

4

### .shape属性访问向量的长度

In [6]:
x.shape

torch.Size([4])

## 2.3.4 矩阵
矩阵是向量的推广

### 实例化矩阵

In [8]:
#实例化矩阵
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

### 矩阵装置

In [9]:
#矩阵装置 
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

### 矩阵比较

In [13]:
#矩阵比较 
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]]) 
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 2.3.5 张量
张量为我们提供了描述具有任意数量轴的n维数组的通用方法

In [15]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 2.3.6 张量算法的基本性质

### 矩阵之间加法

In [16]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4) 
B = A.clone() # 通过分配新内存，将A的一个副本分配给B 
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

### 矩阵和标量之间加法

In [18]:
a = 2 
X = torch.arange(24).reshape(2, 3, 4) 
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

### Hadamard积
两个矩阵的按元素乘法称为*Hadamard积*（Hadamard product）（数学符号$\odot$）

In [19]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

### mean() 求平均值
### numle() 求总数

In [32]:
A.numel(),A.sum(),A.mean(), A.sum() / A.numel()

(20, tensor(190.), tensor(9.5000), tensor(9.5000))

## 2.3.6 降维

### sum()求和函数
调用求和函数会沿所有的轴降低张量的维度，使它变为一个标量

In [21]:
x = torch.arange(4, dtype=torch.float32) 
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [22]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

### 指定张量沿哪一个轴来通过求和降低维度

#### 通过行的元素降维axis=0

In [26]:
# 通过行的元素降维axis=0，所有列元素求和
A_sum_axis0 = A.sum(axis=0)
A,A_sum_axis0, A_sum_axis0.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([40., 45., 50., 55.]),
 torch.Size([4]))

#### 通过列的元素降维axis=1

In [27]:
# 通过列的元素降维axis=1，所有行元素求和
A_sum_axis1 = A.sum(axis=1)
A,A_sum_axis1, A_sum_axis1.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([ 6., 22., 38., 54., 70.]),
 torch.Size([5]))

#### 沿着行列求和

In [28]:
# 沿着行列求和
A.sum(axis=[0, 1])  # Same as `A.sum()`

tensor(190.)

#### 平均值函数降维

In [36]:
A.shape[0],A.sum(axis=0),A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(5,
 tensor([40., 45., 50., 55.]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([ 8.,  9., 10., 11.]))

## 2.3.7 非降维求和

In [38]:
#调用函数来计算总和或均值时保持轴数不变
sum_A = A.sum(axis=1, keepdims=True)
sum_A


tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [39]:
A,A / sum_A

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[0.0000, 0.1667, 0.3333, 0.5000],
         [0.1818, 0.2273, 0.2727, 0.3182],
         [0.2105, 0.2368, 0.2632, 0.2895],
         [0.2222, 0.2407, 0.2593, 0.2778],
         [0.2286, 0.2429, 0.2571, 0.2714]]))

### cumsum()按行计算总和
此函数不会沿任何轴降低输入张量的维度

In [40]:
A,A.cumsum(axis=0),A.cumsum(axis=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.],
         [24., 28., 32., 36.],
         [40., 45., 50., 55.]]),
 tensor([[ 0.,  1.,  3.,  6.],
         [ 4.,  9., 15., 22.],
         [ 8., 17., 27., 38.],
         [12., 25., 39., 54.],
         [16., 33., 51., 70.]]))

## 2.3.8 点积
点积（dotproduct）是相同位置的按元素乘积的和

### dot()执行点积操作

In [41]:
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

### 按元素乘法，然后进行求和

In [43]:
torch.sum(x * y)

tensor(6.)

## 2.3.9 矩阵-向量积
矩阵向量积$\mathbf{A}\mathbf{x}$是一个长度为$m$的列向量，其第$i$个元素是点积$\mathbf{a}^\top_i \mathbf{x}$

### np.dot 求解矩阵向量积
A的列维数（沿轴1的长度）必须与x的维数（其长度）相同。

In [53]:
import numpy as np
np.dot(A,x)

array([ 14.,  38.,  62.,  86., 110.], dtype=float32)

### np.dot 求解矩阵向量积

In [45]:
A,x,A.shape, x.shape, torch.mv(A, x)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

## 2.3.10 矩阵-矩阵乘法
矩阵-矩阵乘法$\mathbf{AB}$看作是简单地执行$m$次矩阵-向量积，并将结果拼接在一起，形成一个$n \times m$矩阵

### mm()矩阵乘法

In [55]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

## 2.3.11 范数
定义：目标，或许是深度学习算法最重要的组成部分（除了数据），被表达为范数。

$L_2$*范数*是向量元素平方和的平方根：
$$\|\mathbf{x}\|_2 = \sqrt{\sum_{i=1}^n x_i^2}$$

$L_1$范数，它表示为向量元素的绝对值之和：
$$\|\mathbf{x}\|_1 = \sum_{i=1}^n \left|x_i \right|$$

矩阵
的*Frobenius范数*（Frobenius norm）是矩阵元素平方和的平方根：
$$\|\mathbf{X}\|_F = \sqrt{\sum_{i=1}^m \sum_{j=1}^n x_{ij}^2}$$

### abs.sum()L1范数求解

In [59]:
torch.abs(u).sum()

tensor(7.)

### norm()L2范数求解

In [56]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

### Frobenius范数范数求解

In [60]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

## 2.3.12 小结

* 标量、向量、矩阵和张量是线性代数中的基本数学对象。

* 向量泛化自标量，矩阵泛化自向量。

* 标量、向量、矩阵和张量分别具有零、一、二和任意数量的轴。

* 一个张量可以通过sum和mean沿指定的轴降低维度。

* 两个矩阵的按元素乘法被称为他们的哈达玛积。它与矩阵乘法不同。

* 在深度学习中，我们经常使用范数，如\(L_1\)范数、\(L_2\)范数和弗罗贝尼乌斯范数。

* 我们可以对标量、向量、矩阵和张量执行各种操作。


## 2.3.13 作业



    证明一个矩阵\(\mathbf{A}\)的转置的转置是\(\mathbf{A}\)：\((\mathbf{A}^\top)^\top = \mathbf{A}\)。

    给出两个矩阵\(\mathbf{A}\)和\(\mathbf{B}\)，显示转置的和等于和的转置：\(\mathbf{A}^\top + \mathbf{B}^\top = (\mathbf{A} + \mathbf{B})^\top\)。

    给定任意方矩阵\(\mathbf{A}\)，\(\mathbf{A} + \mathbf{A}^\top\)总是对称的吗?为什么? 1.我们在本节中定义了形状（2,3,4）的张量X。len(X)的输出结果是什么？ 1.对于任意形状的张量X,len(X)是否总是对应于X特定轴的长度?这个轴是什么? 1.运行A/A.sum(axis=1)，看看会发生什么。你能分析原因吗？ 1.当你在曼哈顿的两点之间旅行时，你需要在坐标上走多远，也就是说，就大街和街道而言？你能斜着走吗？ 1.考虑一个具有形状（2,3,4）的张量，在轴0,1,2上的求和输出是什么形状? 1.向linalg.norm函数提供3个或更多轴的张量，并观察其输出。对于任意形状的张量这个函数计算得到什么?


#### 作业1